"""added None to description and comment

Revision ID: 055e9b937e47
Revises: 5e0a42e48420
Create Date: 2025-05-24 12:43:03.072133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055e9b937e47'
down_revision: Union[str, None] = '5e0a42e48420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('books', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
