"""added book_author_relations

Revision ID: 4bb0f239ca18
Revises: 8048120d45f3
Create Date: 2025-05-26 18:00:13.674194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb0f239ca18'
down_revision: Union[str, None] = '8048120d45f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_author_relations',
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_name'], ['authors.name'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('author_name', 'book_id')
    )
    op.create_index(op.f('ix_book_author_relations_book_id'), 'book_author_relations', ['book_id'], unique=False)
    op.drop_constraint('books_author_name_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'author_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('books_author_name_fkey', 'books', 'authors', ['author_name'], ['name'], ondelete='CASCADE')
    op.drop_index(op.f('ix_book_author_relations_book_id'), table_name='book_author_relations')
    op.drop_table('book_author_relations')
    # ### end Alembic commands ###
